INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (1, null, 'Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (2, null, 'Hardcore Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (3, null, 'Punk Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (7, null, 'Misfits-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (8, null, 'PunknRoll-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (9, null, 'Country-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (10, null, 'Psychobilly-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (11, null, 'Pop-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (12, null, 'Ramones-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (13, null, 'Romantik-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (14, null, 'Hardrock-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (15, null, 'Metal-Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (17, null, 'Other Favorites');
INSERT INTO playlist (P_ID, P_META_DESC, P_NAME) VALUES (18, null, 'Rockabilly-Favorites');
